she_codes_news/news/urls.py
from django.urls import path, re_path
from . import views

app_name = "news"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.StoryView.as_view(), name="story"),
    path("add-story/", views.AddStoryView.as_view(), name="newStory"),
    path("stories-order-by-date/", views.storiesByDateView.as_view(), name="storiedByDate"),
    re_path(r'^author/(?P<author>\d+)$', views.storiesByAuthorView.as_view(), name='storiesByAuthor'),
    # path("authors/<int:author_id>/", views.storiesByAuthorView.as_view(), name="storiesByAuthor"),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("news/", include("news.urls")),
    path("admin/", admin.site.urls),
    path('users/', include('users.urls')),
    path("users/", include("django.contrib.auth.urls")),
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, ViewAccountView, AllUsersView

app_name = "users"

urlpatterns = [
    path("create-account/", CreateAccountView.as_view(), name="createAccount"),
    path("view-account/<int:pk>/", ViewAccountView.as_view(), name="viewAccount"),
    path("", AllUsersView.as_view(), name="allUsers"),
]

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    # author = models.CharField(max_length=200), 
    # on_delete means if you delete a user, it means everything associated with that user will be deleted
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    pub_date = models.DateTimeField()
    content = models.TextField()
    image_url = models.CharField(max_length=500, default="https://picsum.photos/600")

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory


class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ["title", "pub_date", "content", "image_url"]
        widgets = {
            "pub_date": forms.DateInput(
                format=("%m/%d/%Y"), attrs={"class": "form-control", "placeholder": "Select a date", "type": "date"}
            ),
        }

she_codes_news/users/forms.py
from pyexpat import model
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ["username", "email"]


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ["username", "email"]

she_codes_news/news/views.py
from django.views import generic
from .models import NewsStory
from django.urls import reverse_lazy
from .forms import StoryForm


class IndexView(generic.ListView):
    template_name = "news/index.html"

    def get_queryset(self):
        """Return all news stories."""
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["latest_stories"] = NewsStory.objects.all()[:4]
        context["all_stories"] = NewsStory.objects.all()
        context["stories_by_date"] = NewsStory.objects.all().order_by("-pub_date")
        return context


class StoryView(generic.DetailView):
    model = NewsStory
    template_name = "news/story.html"
    context_object_name = "story"


class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = "storyForm"
    template_name = "news/createStory.html"
    success_url = reverse_lazy("news:index")

    # overriding form_valid which is on generic.CreateView
    def form_valid(self, form):
        # to set author to the  user logged in
        form.instance.author = self.request.user
        # call the form_valid on generic.CreateVie
        return super().form_valid(form)

class storiesByDateView(generic.ListView):
    template_name = "news/storiesByDate.html"

    def get_queryset(self):
        """Return all news stories."""
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["stories_by_date"] = NewsStory.objects.all().order_by("-pub_date")
        return context

class storiesByAuthorView(generic.ListView):
    template_name = "news/storiesByAuthor.html"

    def get_queryset(self):
        """Return all news stories."""
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        # author = self.request.GET.get("author")
        author = self.kwargs["author"] # this author refers to the P<author> defined in the url
        print("author", author)
        context = super().get_context_data(**kwargs)
        context["stories_by_author"] = NewsStory.objects.all().filter(author=author)
        return context

she_codes_news/users/views.py
# reverse_lazy: change django to a url
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm

# Create your views here.
# login and logout's views are predefined in django
class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    # reverse_lazy lookup the url path from the saved name
    success_url = reverse_lazy("login")
    template_name = "users/createAccount.html"


class ViewAccountView(generic.DetailView):
    model = CustomUser
    template_name = "users/viewAccount.html"


class AllUsersView(generic.ListView):
    template_name = "users/allUsers.html"

    def get_queryset(self):
        return CustomUser.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["all_users"] = CustomUser.objects.all()

        return context

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %} {% load static %} {% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}" />
{% endblock%} {% block content %}

{% if request.user.is_authenticated %}
<form action="" method="post" class="new-story-form">
  <!-- this token is to protect  -->
  {% csrf_token %}
  <!-- this is to insert a variable -->
  {{ form.as_p }}
  <input type="submit" value="submit" />
</form>
{% else%}
<form action="" method="post" class="new-story-form">
  <!-- this token is to protect  -->
  {% csrf_token %}
  <!-- this is to insert a variable -->
  {{ form.as_p }}
  <button type="submit" disabled>Please login to add a new story</button>
</form>
<a href="{% url 'login' %}">Login now</a>
{% endif %}

{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %} 
{% load static %} 
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}" />
{% endblock%} 

{% block content %}
{% if request.user.is_authenticated %}
<a href="{% url 'news:newStory' %}" class="write-new-story-link"
  ><button>Write a new story</button></a
>
{% endif %}
<h2>Latest News</h2>

<div id="latest-stories">
  {% if latest_stories %} 
  {% for story in latest_stories %} 
  {% include "./storyCard.html" with story=story position=forloop.counter %} 
  {% endfor %}
  {% else %}
  <p>No stories are available.</p>
  {% endif %}
</div>

<h2>All News</h2>
<div id="all-stories">
  {% if latest_stories %} 
  {% for story in all_stories %} 
  {% include "./storyCard.html" with story=story %} 
  {% endfor %} 
  {% else %}
  <p>No stories are available.</p>
  {% endif %}
</div>

{% endblock %}

she_codes_news/news/templates/news/storiesByAuthor.html
{% extends "base.html" %}
{% load static %} 
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}" />
{% endblock%} 

{% block content %}

{% for story in stories_by_author %} 
{% if forloop.first %}
<h2>Stories by {{ story.author }}</h2>
{% endif %}
{% endfor %} 
<div id="stories-by-author">
  {% if stories_by_author %}
  {% for story in stories_by_author %} 
  {% include "./storyCard.html" with story=story %} 
  {% endfor %} 
  {% else %}
  <p>This user is lazy, and has not published any stories</p>
  {% endif %}
</div>
{% endblock%} 

she_codes_news/news/templates/news/storiesByDate.html
{% extends "base.html" %}
{% load static %} 
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}" />
{% endblock%} 


{% block content %}

<h2>Stories by date</h2>
<div id="stories-by-date">
  {% if stories_by_date %} 
  {% for story in stories_by_date %} 
  {% include "./storyCard.html" with story=story %} 
  {% endfor %} 
  {% else %}
  <p>No stories are available.</p>
  {% endif %}
</div>
{% endblock%} 

she_codes_news/news/templates/news/story.html
{% extends "base.html" %} {% load static %} {% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}" />
{% endblock %} {% block content %}
<div id="story-wrapper">
  <h2>{{ story.title }}</h2>
  <h4>{{ story.author }}</h4>
  <div id="story-content">
    <!-- <img src="{% static '/news/images/placeholder-5.jpg' %}" /> -->
    <img src="{{ story.image_url }}" />
    {{ story.content|linebreaks }}
  </div>
</div>
{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
  <a href="{% url 'news:story' story.id %}">
    {% if position < 5 %}
    <!-- <img src="../static/news/images/placeholder-{{ position }}.jpg" /> -->
    <img src="{{ story.image_url }}" />
    {% else %}
    <!-- <img src="https://picsum.photos/600" /> -->
    <img src="{{ story.image_url }}" />
    {% endif %}
    <div class="story-card-text">
      <h3>{{ story.title }}</h3>
      <h4>{{ story.author }}</h4>
      <h4>{{ story.pub_date }}</h4>
    </div>
  </a>
</div>

she_codes_news/templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>She Codes News</title>
    <meta name="description" content="" />
    <meta name="author" content="Ricci" />
    <link
      href="https://fonts.googleapis.com/css?family=Manjari&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
    {% block stylesheets %}{% endblock %}
  </head>

  <body>
    <header>
      <div id="header-text">
        <a id="header-link" href="{% url 'news:index' %}">
          <h1>She {Codes} News</h1>
        </a>
      </div>
      <div id="header-menu">
        {% include './sort.html' %}
        <!-- include nav here -->
        {% include './nav.html' %}
      </div>
    </header>

    <!-- content blocks here -->
    {% block content %}{% endblock %}
  </body>
</html>

she_codes_news/templates/nav.html
<nav>
  <a href="{% url 'news:index' %}">Home</a>
  {% if request.user.is_authenticated %}
  <a href="{% url 'users:viewAccount' user.id %}">{{ user.username}}</a>
  <a href="{% url 'logout' %}">Logout</a>
  {% else%}
  <a href="{% url 'login' %}">Login</a>
  <a href="{% url 'users:createAccount' %}">Sign up</a>
  {% endif %}
</nav>

she_codes_news/templates/sort.html
<ul>
  <a href="{% url 'users:allUsers' %}"><div>View Stories By Author</div></a>
  <a href="{% url 'news:storiedByDate' %}"><div>View Stories By Date</div></a>
</ul>

she_codes_news/users/templates/users/allUsers.html
{% extends "base.html" %} {% block content %}

<h2>Select an author to view their stories</h2>

<div>
  {% if all_users %} 
  {% for user in all_users %} 
  {% include "./userCard.html" with user=user position=forloop.counter %} 
  {% endfor %}
  {% else %}
  <p>No users yet, register now to become our first user!</p>
  <a href="{% url 'users:createAccount' %}">Sign up</a>
  {% endif %}
</div>
{% endblock %}

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %} 

{% block content %}
{% if request.user.is_authenticated %}
<h4>You have already logged in, log out to create another account</h4>
<a href="{% url 'logout' %}">Logout</a>
{% else %}
<h2>Create Account</h2>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Create Account</button>
</form>
{% endif %}
{% endblock %}

she_codes_news/users/templates/users/userCard.html
<div class="story-card">
  <a href="{% url 'news:storiesByAuthor' user.id %}">
    <div>
      <h4>{{ user.username }}</h4>
    </div>
  </a>
</div>

she_codes_news/users/templates/users/viewAccount.html
{% extends 'base.html' %} {% load static %} 

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'users/styles.css' %}" />
{% endblock%} 

{% block content %}

{% if request.user.is_authenticated %}
<h2>Your Profile</h2>

<div class="user-detail-item">
  <h4>Username:</h4>
  <p>{{ user.username}}</p>
</div>
<div class="user-detail-item">
  <h4>Email:</h4>
  <p>{{ user.email}}</p>
</div>
<div class="user-detail-item">
  <h4>Last login:</h4>
  <p>{{ user.last_login }}</p>
</div>
<div class="user-detail-item">
  <h4>Date joined:</h4>
  <p>{{ user.date_joined }}</p>
</div>
{% else %}

<a href="{% url 'login' %}"><h2>Login to view your profile</h2></a>
{% endif %} {% endblock %}